version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: fastapi
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
        restart: true
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata: