FROM python:3.10-slim

WORKDIR /fastapi-app

#install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

#copy project
COPY . .

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80"]